version: "3.9"

services:
  # -------- Laravel Backend --------
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
      - "6001:6001" # WebSocket
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: admin
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: organisation_des_stagiaires
      DB_USERNAME: postgres
      DB_PASSWORD: root
    depends_on:
      - postgres
    volumes:
      - ./backend:/var/www/html
      - laravel_storage:/var/www/html/public/storage

  # -------- PostgreSQL Database --------
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: organisation_des_stagiaires
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data

  # -------- React Frontend --------
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "5173:80"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      CHOKIDAR_USEPOLLING: "true"

volumes:
  pgdata:
  laravel_storage:
