name: Laravel CI

on:
  workflow_dispatch:
  push:
    branches: ["backend"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: organisation_des_stagiaires
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: pdo_pgsql,pgsql,mbstring,xml,bcmath,curl,zip
        ini-values: post_max_size=256M,upload_max_filesize=256M

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      working-directory: ./backend

    - name: Update Composer
      run: composer self-update --2

    - name: Copy composer files
      run: |
        php -r "file_exists('composer.json') || copy('composer.json.example', 'composer.json');"
        php -r "file_exists('composer.lock') || copy('composer.lock.example', 'composer.lock');"

    - name: update Dependencies
      run: composer update
      working-directory: ./backend
    
    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-scripts
      working-directory: ./backend

    - name: Generate Laravel Key
      run: php artisan key:generate
      working-directory: ./backend

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      working-directory: ./backend

    - name: Configure PostgreSQL in .env
      run: |
        php -r "file_put_contents('.env', preg_replace('/DB_CONNECTION=.*/', 'DB_CONNECTION=admin', file_get_contents('.env')));"
        php -r "file_put_contents('.env', preg_replace('/DB_HOST=.*/', 'DB_HOST=127.0.0.1', file_get_contents('.env')));"
        php -r "file_put_contents('.env', preg_replace('/DB_PORT=.*/', 'DB_PORT=5432', file_get_contents('.env')));"
        php -r "file_put_contents('.env', preg_replace('/DB_DATABASE=.*/', 'DB_DATABASE=organisation_des_stagiaires', file_get_contents('.env')));"
        php -r "file_put_contents('.env', preg_replace('/DB_USERNAME=.*/', 'DB_USERNAME=postgres', file_get_contents('.env')));"
        php -r "file_put_contents('.env', preg_replace('/DB_PASSWORD=.*/', 'DB_PASSWORD=root', file_get_contents('.env')));"
      working-directory: ./backend

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h 127.0.0.1 -p 5432; do
          echo "Waiting for database..."
          sleep 2
        done
      working-directory: ./backend

    - name: Run migrations
      run: php artisan migrate --path=database/migrations/admin --force
      working-directory: ./backend

    - name: Seed database
      run: php artisan db:seed --force
      working-directory: ./backend

    - name: Run tests
      run: php artisan test
      working-directory: ./backend